import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1380px',
      '2xl': '1536px',
    },
    container: {
      center: true,
      padding: {
        '2xl': '36px',
      },
      screens: {
        '2xl': '1440px',
      },
    },
    extend: {
      height: {
        header: 'var(--header-height)',
      },
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        tertiary: 'var(--color-tertiary)',
        quaternary: 'var(--color-quaternary)',
        pink: 'var(--color-pink)',
        purple: 'var(--color-purple)',
        'border-pink': 'var(--border-color-pink)',
        'background-pink': 'var(--background-color-pink)',
        'bg-active': 'var(--bg-active)',
        'bg-coins': 'var(--bg-coins)',
        'pink-text': 'var(--text-color-pink)',
        'bg-button-func': 'var(--bg-button)',
        'card-content': 'var(--bg-card-content)',
        'bet-up': 'var(--bet-up)',
        'bet-up-border': 'var(--bet-up-border)',
        'bet-down': 'var(--bet-down)',
        'bet-down-border': 'var(--bet-down-border)',
        'live-card-border': 'var(--border-live-card)',
        'live-card': 'var(--bg-live-card)',
        'text-down': 'var(--text-down)',
        'gray-1': 'var(--gray-1)',
        'green-1': 'var(--green-1)',
      },
      backgroundImage: {
        'hero-pattern': 'linear-gradient(-90deg, var(--color-primary) 0%, var(--color-secondary) 100%)',
        'hero-home': 'linear-gradient(180deg, var(--color-tertiary) 0%, var(--color-quaternary) 100%)',
        'button-pattern': 'linear-gradient(-90deg, var(--color-quinary) 0%, var(--color-quinary-2) 100%)',
        text: 'linear-gradient(to bottom, var(--color-pink) 0%, var(--color-purple) 100%)',
        'card-game': 'var(--gradient-game-card)',
        'border-gradient-game-card': 'var(--border-gradient-game-card)',
        'border-gradient-button-faucet': 'var(--border-gradient-button-faucet)',
        'border-gradient-button-mint': 'var(--border-gradient-button-mint)',
        'gradient-bet': 'var(--bg-gradient-bet)',
        'border-gradient-bet': 'var(--border-gradient-bet)',
        'trading-view': 'var(--gradient-trading-view)',
        'gradient-button': 'var(--gradient-button)',
        'gradient-collect': 'var(--gradient-collect)',
        'gradient-border-bt': 'var(--border-gradient-button)',
        'gradient-text-stroke': 'var(--gradient-text-stroke)',
        'gradient-rank-gold': 'var(--gradient-rank-gold)',
        'gradient-rank-silver': 'var(--gradient-rank-silver)',
        'gradient-rank-purple': 'var(--gradient-rank-purple)',
        'gradient-rank-blue': 'var(--gradient-rank-blue)',
        'gradient-rank-green': 'var(--gradient-rank-green)',
        'gradient-rank-black': 'var(--gradient-rank-black)',
        'gradient-unranked': 'var(--gradient-unranked)',
      },
      fontFamily: {
        poppins: ['"Poppins"', 'sans-serif'],
        roboto: ['"Roboto"', 'sans-serif'],
        pressStart2P: ['"Press Start 2P"', 'sans-serif'],
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};
export default config;
